#!/bin/bash

# Install RSL_in_IDL
#
# Syntax:
#     rslinstall [-f] [dir]
#

usage()
{
    echo "Usage: rslinstall [-f] [dir]"
    echo "Install rsl_in_idl.  If directory argument is given, install it there."
    echo "Default directory is $HOME/idl/rsl_in_idl."
    echo "Options:"
    echo "  -f     force overwrite of existing directory"
}

# Check for --help or -h.
case "$1" in
    --h*|-h) usage; exit 0;;
esac

while getopts "fh" opt; do
    case "$opt" in
	f) overwrite=overwrite;;
	h) usage; exit 0;;
	*) usage; exit 0;;
    esac
done

let 'OPTIND -= 1'
shift $OPTIND

# Check for target directory argument.  If not given, use default.

if [ $# -gt 0 ]; then
    rsldir=`realpath $1` # Get full path name.
else
    # Set default target directory.
    if [ -d $HOME/idl ]; then
	rsldir=$HOME/idl/rsl_in_idl
    else
	rsldir=$HOME/rsl_in_idl
    fi
fi

# If directory exists and force-overwrite option not given, ask permission.

if [ -e $rsldir ] && [ -z "$overwrite" ]; then
    read -p "$rsldir exists. Overwrite? (y or n) " reply
    case "$reply" in
	[yY]*) reply=yes;;
	    *) echo Nothing installed.; exit 0;;
    esac
fi

# If target directory doesn't exist, create it and its subdirectories.
if [ ! -d "$rsldir" ]; then
    mkdir -p $rsldir || exit 1
fi

echo "Installing rsl_in_idl in directory $rsldir."
cp -r -p . $rsldir || exit 1
echo "Done"
