geo_match_3d_dsd_comparisons, INSTRUMENT=instrument, $
   SPEED=looprate, $
   ELEVS2SHOW=1.3, $
   NCPATH='/data/gpmgv/netcdf/geo_match/GPM/2ADPR/NS/V03B/1_2/2015', $
   SITE='KAKQ', $
   NO_PROMPT=no_prompt, $
   PPI_VERTICAL=ppi_vertical, $
   PPI_SIZE=250, $
   PCT_ABV_THRESH=70, $
   MAX_RANGE=max_range_in, $
   SHOW_THRESH_PPI=show_thresh_ppi, $
   Z_ONLY_PPI=z_only_ppi, $
   GV_CONVECTIVE=0, $
   GV_STRATIFORM=0, $
   ALT_BB_HGT=alt_bb_hgt, $
   HIDE_TOTALS=hide_totals, $
   HIDE_RNTYPE=1, $
   HIDE_PPIS=hide_ppis, $
   PS_DIR=ps_dir, $
   B_W=b_w, $
   BATCH=batch, $
   S2KU = s2ku, $
   USE_ZR = use_zr, $
   DZERO_ADJ = dzero_adj, $
   GR_RR_FIELD='RR', $
   GR_DM_FIELD='Dm', $
   GR_NW_FIELD='N2', $
   RECALL_NCPATH=1, $
   SUBSET_METHOD=subset_method, $
   MIN_FOR_SUBSET=min_for_subset, $
   SAVE_DIR=save_dir, $
   STEP_MANUAL=step_manual, $
   DECLUTTER=0

